apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cool-app-cool-app-quarkus-java-prod
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    system: cool-app
spec:
  project: default
  source:
    repoURL: https://github.com/llowinge/developer-charts
    targetRevision: HEAD
    path: quarkus-application
    helm:
      values: |
        system: cool-app
        component: cool-app-quarkus-java
        environment: prod
        image:
          tag: latest
        replicaCount: 0
  destination:
    server: https://kubernetes.default.svc
    namespace: cool-app-prod
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=false
    - RespectIgnoreDifferences=true
    - ApplyOutOfSyncOnly=true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 10m